from .catalog_helpers import regional_globo

GLOBOPLAY_REGIONAL_B = [
    regional_globo("globoplay-bom-dia-es","Bom Dia ES","ES","Sudeste",["TV Gazeta ES"],"https://globoplay.globo.com/v/11645540/"),
    regional_globo("globoplay-gazeta-meio-dia-es","Gazeta Meio Dia","ES","Sudeste",["ESTV 1ª Edição","ESTV1","ES1"],"https://globoplay.globo.com/v/5423638/"),
    regional_globo("globoplay-estv2","ESTV 2ª Edição","ES","Sudeste",["ESTV2","ES2"]),
    regional_globo("globoplay-bom-dia-minas","Bom Dia Minas","MG","Sudeste",["Globo Minas"],"https://globoplay.globo.com/v/5535965/"),
    regional_globo("globoplay-mg1","MG1","MG","Sudeste",["MGTV 1ª Edição","MG Primeira Edição"],"https://globoplay.globo.com/v/12552834/"),
    regional_globo("globoplay-mg2","MG2","MG","Sudeste",["MGTV 2ª Edição","MG Segunda Edição"]),
    regional_globo("globoplay-bom-dia-rio","Bom Dia Rio","RJ","Sudeste",landing_override="https://globoplay.globo.com/v/8383434/"),
    regional_globo("globoplay-rj1","RJ1","RJ","Sudeste",["RJTV 1ª Edição","RJ Primeira Edição"],"https://globoplay.globo.com/v/5976232/"),
    regional_globo("globoplay-rj2","RJ2","RJ","Sudeste",["RJTV 2ª Edição","RJ Segunda Edição"],"https://globoplay.globo.com/v/12954402/"),
    regional_globo("globoplay-bom-dia-sp","Bom Dia SP","SP","Sudeste",["Bom Dia São Paulo","BDSP"],"https://globoplay.globo.com/v/5701776/"),
    regional_globo("globoplay-sp1","SP1","SP","Sudeste",["SPTV 1ª Edição","SP Primeira Edição"],"https://globoplay.globo.com/v/12096579/"),
    regional_globo("globoplay-sp2","SP2","SP","Sudeste",["SPTV 2ª Edição","SP Segunda Edição"],"https://globoplay.globo.com/v/5854721/"),
    regional_globo("globoplay-bom-dia-cidade-eptv","Bom Dia Cidade • EPTV","SP","Sudeste",["EPTV Campinas","EPTV Ribeirão","EPTV Central"]),
    regional_globo("globoplay-eptv1","EPTV1","SP","Sudeste",["EPTV 1ª Edição"]),
    regional_globo("globoplay-eptv2","EPTV2","SP","Sudeste",["EPTV 2ª Edição"]),
    regional_globo("globoplay-bom-dia-cidade-tem","Bom Dia Cidade • TV TEM","SP","Sudeste",["TV TEM"]),
    regional_globo("globoplay-tem-noticias-1","TEM Notícias 1ª Edição","SP","Sudeste",["TV TEM 1ª Edição"]),
    regional_globo("globoplay-tem-noticias-2","TEM Notícias 2ª Edição","SP","Sudeste",["TV TEM 2ª Edição"]),
    regional_globo("globoplay-bom-dia-regiao-tribuna","Bom Dia Região • TV Tribuna","SP","Sudeste",["TV Tribuna Santos"]),
    regional_globo("globoplay-jornal-tribuna-1","Jornal Tribuna 1ª Edição","SP","Sudeste",["JT1","TV Tribuna"]),
    regional_globo("globoplay-jornal-tribuna-2","Jornal Tribuna 2ª Edição","SP","Sudeste",["JT2","TV Tribuna"]),
    regional_globo("globoplay-bom-dia-fronteira","Bom Dia Fronteira","SP","Sudeste",["TV Fronteira"]),
    regional_globo("globoplay-fronteira-noticias-1","Fronteira Notícias 1ª Edição","SP","Sudeste",["TV Fronteira 1ª Edição"]),
    regional_globo("globoplay-fronteira-noticias-2","Fronteira Notícias 2ª Edição","SP","Sudeste",["TV Fronteira 2ª Edição"]),
    regional_globo("globoplay-bom-dia-vanguarda","Bom Dia Vanguarda","SP","Sudeste",["TV Vanguarda"]),
    regional_globo("globoplay-link-vanguarda","Link Vanguarda","SP","Sudeste",["TV Vanguarda 1ª Edição"]),
    regional_globo("globoplay-jornal-vanguarda","Jornal Vanguarda","SP","Sudeste",["TV Vanguarda 2ª Edição"]),
    regional_globo("globoplay-bom-dia-parana","Bom Dia Paraná","PR","Sul",["RPC"]),
    regional_globo("globoplay-meio-dia-parana","Meio Dia Paraná","PR","Sul",["RPC 1ª Edição"]),
    regional_globo("globoplay-boa-noite-parana","Boa Noite Paraná","PR","Sul",["RPC 2ª Edição"]),
    regional_globo("globoplay-bom-dia-sc","Bom Dia Santa Catarina","SC","Sul",["Bom Dia SC","NSC TV"]),
    regional_globo("globoplay-jornal-do-almoco-sc","Jornal do Almoço • SC","SC","Sul",["NSC TV 1ª Edição","Jornal do Almoço"]),
    regional_globo("globoplay-nsc-noticias","NSC Notícias","SC","Sul",["NSC TV 2ª Edição"]),
    regional_globo("globoplay-bom-dia-rio-grande","Bom Dia Rio Grande","RS","Sul",["RBS TV"],"https://globoplay.globo.com/v/12316554/"),
    regional_globo("globoplay-jornal-do-almoco-rs","Jornal do Almoço • RS","RS","Sul",["RBS TV 1ª Edição","Jornal do Almoço"]),
    regional_globo("globoplay-rbs-noticias","RBS Notícias","RS","Sul",["RBS TV 2ª Edição"]),
]
