from .catalog_helpers import regional_globo

GLOBOPLAY_REGIONAL_A = [
    regional_globo("globoplay-bom-dia-acre","Bom Dia Acre","AC","Norte",["BDAC","Rede Amazônica Acre"]),
    regional_globo("globoplay-jac1","Jornal do Acre 1ª Edição","AC","Norte",["JAC1","Jornal do Acre 1"]),
    regional_globo("globoplay-jac2","Jornal do Acre 2ª Edição","AC","Norte",["JAC2","Jornal do Acre 2"]),
    regional_globo("globoplay-bom-dia-amapa","Bom Dia Amapá","AP","Norte"),
    regional_globo("globoplay-jap1","Jornal do Amapá 1ª Edição","AP","Norte",["JAP1","Jornal do Amapá 1"]),
    regional_globo("globoplay-jap2","Jornal do Amapá 2ª Edição","AP","Norte",["JAP2","Jornal do Amapá 2"]),
    regional_globo("globoplay-bom-dia-amazonia-am","Bom Dia Amazônia","AM","Norte",["Bom Dia Amazonas","Rede Amazônica Amazonas"]),
    regional_globo("globoplay-jam1","Jornal do Amazonas 1ª Edição","AM","Norte",["JAM1","JAM 1ª Edição"]),
    regional_globo("globoplay-jam2","Jornal do Amazonas 2ª Edição","AM","Norte",["JAM2","JAM 2ª Edição"]),
    regional_globo("globoplay-bom-dia-para","Bom Dia Pará","PA","Norte",["TV Liberal"]),
    regional_globo("globoplay-jl1","Jornal Liberal 1ª Edição","PA","Norte",["JL1","Jornal Liberal 1","TV Liberal"]),
    regional_globo("globoplay-jl2","Jornal Liberal 2ª Edição","PA","Norte",["JL2","Jornal Liberal 2","TV Liberal"]),
    regional_globo("globoplay-bom-dia-santarem","Bom Dia Santarém","PA","Norte",["TV Tapajós"]),
    regional_globo("globoplay-tj1-tapajos","Jornal Tapajós 1ª Edição","PA","Norte",["TJ1","Jornal Tapajós 1","TV Tapajós"],"https://globoplay.globo.com/v/6897326/"),
    regional_globo("globoplay-tj2-tapajos","Jornal Tapajós 2ª Edição","PA","Norte",["TJ2","Jornal Tapajós 2","TV Tapajós"],"https://globoplay.globo.com/v/13630892/"),
    regional_globo("globoplay-bom-dia-amazonia-ro","Bom Dia Amazônia","RO","Norte",["Bom Dia Rondônia","Rede Amazônica Rondônia"]),
    regional_globo("globoplay-jro1","Jornal de Rondônia 1ª Edição","RO","Norte",["JRO1","Jornal de Rondônia 1"]),
    regional_globo("globoplay-jro2","Jornal de Rondônia 2ª Edição","RO","Norte",["JRO2","Jornal de Rondônia 2"]),
    regional_globo("globoplay-bom-dia-amazonia-rr","Bom Dia Amazônia","RR","Norte",["Bom Dia Roraima","Rede Amazônica Roraima"]),
    regional_globo("globoplay-jrr1","Jornal de Roraima 1ª Edição","RR","Norte",["JRR1","Jornal de Roraima 1"]),
    regional_globo("globoplay-jrr2","Jornal de Roraima 2ª Edição","RR","Norte",["JRR2","Jornal de Roraima 2"]),
    regional_globo("globoplay-bom-dia-tocantins","Bom Dia Tocantins","TO","Norte",["TV Anhanguera Tocantins"]),
    regional_globo("globoplay-ja1-to","Jornal Anhanguera 1ª Edição Tocantins","TO","Norte",["JA1 Tocantins","JA 1ª Edição Tocantins"]),
    regional_globo("globoplay-ja2-to","Jornal Anhanguera 2ª Edição Tocantins","TO","Norte",["JA2 Tocantins","JA 2ª Edição Tocantins"]),
    regional_globo("globoplay-bom-dia-alagoas","Bom Dia Alagoas","AL","Nordeste",["TV Gazeta AL"]),
    regional_globo("globoplay-al1","AL1","AL","Nordeste",["AL 1ª Edição","ALTV 1ª Edição"]),
    regional_globo("globoplay-al2","AL2","AL","Nordeste",["AL 2ª Edição","ALTV 2ª Edição"]),
    regional_globo("globoplay-jornal-da-manha-ba","Jornal da Manhã","BA","Nordeste",["TV Bahia","Jornal da Manhã Bahia","Bom Dia Bahia"]),
    regional_globo("globoplay-bahia-meio-dia","Bahia Meio Dia","BA","Nordeste",["BMD","TV Bahia 1ª Edição"]),
    regional_globo("globoplay-batv","BATV","BA","Nordeste",["Bahia TV","TV Bahia 2ª Edição"]),
    regional_globo("globoplay-bom-dia-ceara","Bom Dia Ceará","CE","Nordeste",["TV Verdes Mares"]),
    regional_globo("globoplay-cetv1","CETV 1ª Edição","CE","Nordeste",["CETV1","CE1"]),
    regional_globo("globoplay-cetv2","CETV 2ª Edição","CE","Nordeste",["CETV2","CE2"]),
    regional_globo("globoplay-bom-dia-mirante","Bom Dia Mirante","MA","Nordeste",["TV Mirante"]),
    regional_globo("globoplay-jmtv1","JMTV 1ª Edição","MA","Nordeste",["JMTV1","Jornal Mirante 1ª Edição"]),
    regional_globo("globoplay-jmtv2","JMTV 2ª Edição","MA","Nordeste",["JMTV2","Jornal Mirante 2ª Edição"]),
    regional_globo("globoplay-bom-dia-paraiba","Bom Dia Paraíba","PB","Nordeste",["TV Cabo Branco"]),
    regional_globo("globoplay-jpb1","JPB1","PB","Nordeste",["JPB 1ª Edição","Jornal da Paraíba 1ª Edição"]),
    regional_globo("globoplay-jpb2","JPB2","PB","Nordeste",["JPB 2ª Edição","Jornal da Paraíba 2ª Edição"]),
    regional_globo("globoplay-bom-dia-pe","Bom Dia Pernambuco","PE","Nordeste",["Bom Dia PE","Globo Pernambuco"]),
    regional_globo("globoplay-ne1","NE1","PE","Nordeste",["NETV 1ª Edição","NE 1ª Edição"]),
    regional_globo("globoplay-ne2","NE2","PE","Nordeste",["NETV 2ª Edição","NE 2ª Edição"]),
    regional_globo("globoplay-bom-dia-piaui","Bom Dia Piauí","PI","Nordeste",["TV Clube"]),
    regional_globo("globoplay-pi1","PI1","PI","Nordeste",["PITV 1ª Edição","PI 1ª Edição"]),
    regional_globo("globoplay-pi2","PI2","PI","Nordeste",["PITV 2ª Edição","PI 2ª Edição"]),
    regional_globo("globoplay-bom-dia-rn","Bom Dia RN","RN","Nordeste",["Inter TV Cabugi"]),
    regional_globo("globoplay-rn1","RN1","RN","Nordeste",["RNTV 1ª Edição","RN 1ª Edição"]),
    regional_globo("globoplay-rn2","RN2","RN","Nordeste",["RNTV 2ª Edição","RN 2ª Edição"]),
    regional_globo("globoplay-bom-dia-sergipe","Bom Dia Sergipe","SE","Nordeste",["TV Sergipe"]),
    regional_globo("globoplay-se1","SE1","SE","Nordeste",["SETV 1ª Edição","SE 1ª Edição"]),
    regional_globo("globoplay-se2","SE2","SE","Nordeste",["SETV 2ª Edição","SE 2ª Edição"]),
    regional_globo("globoplay-bom-dia-df","Bom Dia DF","DF","Centro-Oeste",["Globo Brasília"]),
    regional_globo("globoplay-df1","DF1","DF","Centro-Oeste",["DFTV 1ª Edição","DF 1"],"https://globoplay.globo.com/v/14711882/"),
    regional_globo("globoplay-df2","DF2","DF","Centro-Oeste",["DFTV 2ª Edição","DF 2"]),
    regional_globo("globoplay-bom-dia-goias","Bom Dia Goiás","GO","Centro-Oeste",["TV Anhanguera"]),
    regional_globo("globoplay-ja1-go","Jornal Anhanguera 1ª Edição","GO","Centro-Oeste",["JA1 Goiás","JA 1ª Edição"]),
    regional_globo("globoplay-ja2-go","Jornal Anhanguera 2ª Edição","GO","Centro-Oeste",["JA2 Goiás","JA 2ª Edição"]),
    regional_globo("globoplay-bom-dia-mt","Bom Dia Mato Grosso","MT","Centro-Oeste",["TV Centro América"]),
    regional_globo("globoplay-mt1","MT1","MT","Centro-Oeste",["MTTV 1ª Edição","MT 1ª Edição"]),
    regional_globo("globoplay-mt2","MT2","MT","Centro-Oeste",["MTTV 2ª Edição","MT 2ª Edição"]),
    regional_globo("globoplay-bom-dia-ms","Bom Dia MS","MS","Centro-Oeste",["TV Morena"]),
    regional_globo("globoplay-mstv1","MSTV 1ª Edição","MS","Centro-Oeste",["MS1","MSTV1"]),
    regional_globo("globoplay-mstv2","MSTV 2ª Edição","MS","Centro-Oeste",["MS2","MSTV2"]),
]
