from __future__ import annotations

DEFAULT_MONITOR_TERMS: tuple[str, ...] = (
    "Marinha do Brasil",
    "Capitania dos Portos",
    "Distrito Naval",
    "NAM Atlântico",
    "Cisne Branco",
    "Fragata Marinha do Brasil",
    "Navio-Patrulha Marinha",
    "Programa Nuclear da Marinha",
    "CAPITANIA FLUVIAL",
    "MARINHA",
    "EXÉRCITO",
    "STM",
    "FAB",
    "FORÇA AÉREA BRASILEIRA",
    "FORÇAS ARMADAS",
    "FRAGATA",
    "SUBMARINO",
    "MAIOR NAVIO DA AMÉRICA LATINA",
    "MANCHAS DE ÓLEO",
    "MILITARES",
    "MILITAR",
    "MINISTRO DA DEFESA",
    "MINISTÉRIO DA DEFESA",
    "PROSUB",
    "ENGEPRON",
)
