import argparse
import os
import sys
import time
import urllib.parse
from pathlib import Path

from PySide6.QtCore import QTimer, QUrl
from PySide6.QtNetwork import QNetworkProxy
from PySide6.QtWebEngineCore import QWebEnginePage, QWebEngineProfile
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import QApplication, QDialog, QHBoxLayout, QLabel, QMessageBox, QPushButton, QVBoxLayout

APP_NAME = "Monitor de Notícias — Extrator de Vídeos"
GLOBOPLAY_URL = "https://globoplay.globo.com/"


def proxy_from_env():
    raw = str(os.environ.get("MONITOR_GLOBOPLAY_PROXY", "") or "").strip()
    if not raw:
        return None
    if "://" not in raw:
        raw = "http://" + raw
    parsed = urllib.parse.urlsplit(raw)
    host = parsed.hostname or ""
    if not host:
        raise ValueError("Servidor do proxy inválido.")
    scheme = (parsed.scheme or "http").lower()
    if scheme in ("socks5", "socks5h", "socks"):
        proxy_type = QNetworkProxy.ProxyType.Socks5Proxy
        default_port = 1080
    else:
        proxy_type = QNetworkProxy.ProxyType.HttpProxy
        default_port = 8080
    port = int(parsed.port or default_port)
    user = urllib.parse.unquote(parsed.username or "")
    password = urllib.parse.unquote(parsed.password or "")
    return QNetworkProxy(proxy_type, host, port, user, password)


def cookie_bytes(cookie):
    name = bytes(cookie.name()).decode("utf-8", "replace").replace("\t", "").replace("\r", "").replace("\n", "").strip()
    value = bytes(cookie.value()).decode("utf-8", "replace").replace("\t", "").replace("\r", "").replace("\n", "").strip()
    return name, value


def cookie_priority(cookie):
    domain = str(cookie.domain() or "").lower().lstrip(".")
    if domain == "globoplay.globo.com" or domain.endswith(".globoplay.globo.com"):
        return 0
    if domain == "play.globo.com" or domain.endswith(".play.globo.com"):
        return 1
    if domain == "login.globo.com" or domain.endswith(".login.globo.com"):
        return 2
    if domain == "globo.com" or domain.endswith(".globo.com"):
        return 3
    if domain == "globoplay.com" or domain.endswith(".globoplay.com"):
        return 4
    return 99


def build_android_cookie_jar(cookies):
    merged = {}
    for cookie in sorted(list(cookies or []), key=cookie_priority):
        if cookie_priority(cookie) >= 99:
            continue
        name, value = cookie_bytes(cookie)
        if name:
            merged[name] = value
    if not merged:
        raise RuntimeError(
            "Nenhum cookie Globo/Globoplay foi encontrado. Faça o login na página principal e tente salvar novamente."
        )
    expiry = int(time.time()) + 30 * 24 * 60 * 60
    lines = ["# Netscape HTTP Cookie File", "# Generated by Monitor de Notícias — Extrator de Vídeos"]
    for name, value in merged.items():
        lines.append("\t".join([".globo.com", "TRUE", "/", "TRUE", str(expiry), name, value]))
    return "\n".join(lines) + "\n", len(merged)


class LoginDialog(QDialog):
    def __init__(self, output_path: Path, profile_dir: Path):
        super().__init__()
        self.output_path = output_path
        self.cookies = {}
        self.saved = False
        self.setWindowTitle("Globoplay — Login dentro do Extrator")
        self.resize(1080, 780)

        root = QVBoxLayout(self)
        info = QLabel(
            "Entre normalmente na sua conta pela página principal do Globoplay. "
            "A senha fica somente na página oficial da Globo. Quando terminar, clique em "
            "SALVAR SESSÃO E VOLTAR. Não é necessário abrir vídeo nem obter códigos manualmente."
        )
        info.setWordWrap(True)
        root.addWidget(info)

        self.status = QLabel("Status: faça o login na página principal do Globoplay.")
        self.status.setWordWrap(True)
        root.addWidget(self.status)

        profile_dir.mkdir(parents=True, exist_ok=True)
        cache_dir = profile_dir / "cache"
        cache_dir.mkdir(parents=True, exist_ok=True)
        self.profile = QWebEngineProfile("ExtratorVideosGloboplay", self)
        self.profile.setPersistentStoragePath(str(profile_dir))
        self.profile.setCachePath(str(cache_dir))
        try:
            self.profile.setPersistentCookiesPolicy(QWebEngineProfile.PersistentCookiesPolicy.ForcePersistentCookies)
        except Exception:
            pass

        self.view = QWebEngineView(self)
        self.page = QWebEnginePage(self.profile, self.view)
        self.view.setPage(self.page)
        root.addWidget(self.view, 1)

        store = self.profile.cookieStore()
        store.cookieAdded.connect(self.cookie_added)
        store.loadAllCookies()

        actions = QHBoxLayout()
        self.btn_home = QPushButton("ABRIR GLOBOPLAY")
        self.btn_save = QPushButton("SALVAR SESSÃO E VOLTAR")
        self.btn_close = QPushButton("FECHAR")
        actions.addWidget(self.btn_home)
        actions.addWidget(self.btn_save)
        actions.addStretch(1)
        actions.addWidget(self.btn_close)
        root.addLayout(actions)

        self.btn_home.clicked.connect(lambda: self.view.setUrl(QUrl(GLOBOPLAY_URL)))
        self.btn_save.clicked.connect(self.save_session)
        self.btn_close.clicked.connect(self.reject)
        self.view.setUrl(QUrl(GLOBOPLAY_URL))

    def cookie_added(self, cookie):
        try:
            name, _ = cookie_bytes(cookie)
            if not name:
                return
            key = (str(cookie.domain() or ""), str(cookie.path() or "/"), name)
            self.cookies[key] = cookie
        except Exception:
            pass

    def save_session(self):
        self.btn_save.setEnabled(False)
        self.status.setText("Status: coletando cookies da sessão…")
        try:
            self.profile.cookieStore().loadAllCookies()
        except Exception:
            pass
        QTimer.singleShot(1200, self.finish_save)

    def finish_save(self):
        try:
            raw, count = build_android_cookie_jar(list(self.cookies.values()))
            self.output_path.parent.mkdir(parents=True, exist_ok=True)
            self.output_path.write_text(raw, encoding="utf-8")
            self.saved = True
            self.status.setText(f"Status: sessão coletada ({count} cookies). Voltando ao Monitor…")
            QMessageBox.information(
                self,
                APP_NAME,
                "Sessão do Globoplay coletada com sucesso.\n\nAgora é só colar o link, escolher a qualidade e baixar."
            )
            self.accept()
        except Exception as exc:
            self.btn_save.setEnabled(True)
            self.status.setText("Status: não foi possível salvar a sessão.")
            QMessageBox.warning(self, APP_NAME, str(exc))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    parser.add_argument("--profile-dir", required=True)
    args = parser.parse_args()

    previous_proxy = QNetworkProxy.applicationProxy()
    try:
        proxy = proxy_from_env()
        if proxy is not None:
            QNetworkProxy.setApplicationProxy(proxy)

        app = QApplication(sys.argv[:1])
        app.setApplicationName(APP_NAME)
        dialog = LoginDialog(Path(args.output), Path(args.profile_dir))
        result = dialog.exec()
        return 0 if result == QDialog.DialogCode.Accepted and dialog.saved else 2
    except Exception as exc:
        try:
            QMessageBox.critical(None, APP_NAME, str(exc))
        except Exception:
            pass
        return 3
    finally:
        try:
            QNetworkProxy.setApplicationProxy(previous_proxy)
        except Exception:
            pass


if __name__ == "__main__":
    raise SystemExit(main())
